github_url: https://github.com/
google_url: https://plus.google.com/+GeekSlider
linkedin_url: https://in.linkedin.com/in/ronnietbaby
about_url: /about/
archive_url: /archive/
projects_url: /projects/
contact_url: /contact/
disclaimer_url: /disclaimer/
rss_url: /atom.xml
sitemap_url: /sitemap.xml
